### PR TITLE
Changed type of display from div to input[type=number]

### PR DESCRIPTION
**Pull request by pogramos**
allows manual input besides the increase and decrease controls.

### CODE REVIEW

**Comment by rajeshwarpatlolla** [comment]
This does not support `00` let's say when the time is 03:00 PM.

**Comment by pogramos** [comment]
Indeed that does not support 00, my bad.

this way you can still use 00 with both manual input and controls, the $watch will keep the fields safe from letters and special characters

**Comment by distrotek** [comment]
input[type=tel]

**Comment by distrotek** [comment]
It works really nicely if you change the inputs to type "tel" and then remove the `scope.time.hours = "00";` from the watch expressions.

**Comment by rajeshwarpatlolla** [comment]
We are not allowing the users to click on the input box. They are not input fields. It is just a `div` with some `CSS`.

**Pull request closed without merging**
