### PR TITLE
Added support for showing time in local time, regardless of timezone

### PR DESCRIPTION
**Pull request by vicpon**

### CODE REVIEW

**Comment by rajeshwarpatlolla** [comment]
Have you testing with the modifications you did? is it working fine?

**Comment by vicpon** [comment]
Yes, I already started using it in an app. Thanks for the directive by the way!

Sent by Mailwise – Your emails, with style.:)

-------- Original Message --------

**Comment by rajeshwarpatlolla** [comment]
@wujitouch, thanks for using my directive/bower component and always welcome.

**Comment by rajeshwarpatlolla** [comment]
@wujitouch, Have you tested with your code. Is it working properly for all the time zones?

**Comment by vicpon** [comment]
Hi, I did not checked all time zones but I have found and corrected some bugs since my initial push.

Sent by Mailwise – Your emails, with style.:)

-------- Original Message --------

**Comment by rajeshwarpatlolla** [comment]
I have implemented as per the UTC time zone, so when you pass 18000, it always considers `5 AM` irrespective of the time zone.

**Comment by vicpon** [comment]
TBH, I think it would be more convenient to use a Date object instead of epoch. I changed it to use a Date object and that should handle user timezones. I'll push it to you for review

-------- Original Message --------

**Pull request closed without merging**
