### PR TITLE
Added support for optional title

### PR DESCRIPTION
**Pull request by FoCoPeazy**
Added optional 'title' parameter to set the popup window title

### CODE REVIEW

**Comment by rajeshwarpatlolla** [comment]
There are few other things needs to be changed like template, README.md  file for information and i will make a few other minor changes and will implement this feature in the next release.

**Comment by FoCoPeazy** [comment]
@rajeshwarpatlolla Sounds great, nice work on this and ionic-datepicker as well!

**Comment by rajeshwarpatlolla** [comment]
@FoCoPeazy , Thanks for making a pull request with a nice feature.

**Comment by rajeshwarpatlolla** [comment]
Thanks for making PR.

**Pull request merged**
