### PR TITLE
Fix bug that caused hour to increase by 1 when minutes was > 30.

### PR DESCRIPTION
**Pull request by dts**

### CODE REVIEW

**Comment by rajeshwarpatlolla** [comment]
Could you please explain what is the issue?

**Comment by dts** [comment]
When you open the time picker with minutes of 30 to 59 it increases the hours by 1.

**Comment by apizzini** [comment]
I had the same problem and solved in the exact same way!

**Comment by rajeshwarpatlolla** [comment]
Thanks for your PR @dts.

**Pull request merged**
